### ISSUE TITLE
데이터 입력폼을 데이터 형태에 따라 구분합니다

### ISSUE THREAD

**Issue by rest515** [parti-coop/datapublic#26]
데이터 형태는

- 주제별 아카이브 링크
- csv, xls 등 숫자 데이터
- 기록물
- 뉴스나 기사 등 스토리

**Comment by Mee-parti** [comment]
구글 스프레드시트와 드라이브를 활용해 데이터를 입력할 수 있도록 합니다.
데이터 페이지로 데이터시트를 임베이드해서 보여질 수 있는 도록 고려합니다.

**Comment by JP925** [comment]
데이터 검증을 위한 관리 프로세스를 만듭니다.

**Comment by Mee-parti** [comment]
https://docs.google.com/spreadsheets/d/1y8_iGPQaeVTluLn5B6ZxK2HwFEfARoaxpWcHlFUVrMY/edit#gid=1508127997
위의 엑셀시트와 같이 데이터 입력 포맷을 구성합니다.
아래에 예를 들어 기능 목록을 보여드립니다.
검색
데이터 명 
데이터 속성 (예) 
1. 데이터명: 경상북도 코로나바이러스19 발생동향 
  1-1. 데이터 한줄 설명: 경상북도의 코로나19 발생동향, 현황을 제공하는 데이터 
2. 데이터 출처: http://www.gb.go.kr/Main/open_contents/section/wel/page.do?mnu_uid=5760&LARGE_CODE=360&MEDIUM_CODE=10&SMALL_CODE=50&SMALL_CODE2=60mnu_order=2
3. 파일형식: html
4. 관리기관: 경상북도
5. 데이터 속성
- 구분
- 확진환자현황 : 계, 격리중, 해제, 사망
- 검사현황 : 계, 검사중, 음성
- 접촉자 : 계, 격리중, 음성
6. 데이터 생성일
    6-1. 원본생성일: 
    6-2. 수정일: 2020.08.26 08시 기준
7. 라이선스 
8. 데이터 참고사항 
- 본 데이터는 2020년 8월 26일 08시 기준이며 지속적으로 업데이트 됨

**Comment by rest515** [comment]
속성을 추가하였습니다. 확인해 보셔요.
