### ISSUE TITLE
오류가 발생하면 슬랙으로 알림이 보내집니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/datapublic#36]
서버의 ERROR_SLACK_WEBHOOK_URL 라는 환경 변수에 슬랙 웹훅 주소를 넣어 둘께요.

**Comment by rest515** [comment]
넵!

**Comment by wagurano** [comment]
@MartianLee  
notification
gem 'slack-notifier'
gem 'exception_notification'
