### ISSUE TITLE
게시판 기능과 아카이브 기능을 연결합니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/datapublic#38]
콘텐츠 포스팅을 할때는 해당 아카이브(공유기업, 단체별)에서 포스트와 데이터 다 보였으면 합니다.
또 포스트에 들어가서는 아카이브별로 볼 수 있었으면 합니다.
게시판 기능과 아카이브 기능이 연동되었으면 합니다.

**Comment by rest515** [comment]
컨텐츠를 포스팅할때 아카이브를 지정할 수 있도록 해달란 요청이신 거죠? 그렇게 지정하면, 해당 아카이브 페이지에서 포스트 목록도 볼 수 있었으면 한다는 요청일까요?

그리고 포스트에 들어가서는 아카이브별로 무엇이 보인다는 것일까요? 아카이브별로 데이터일까요? 포스트일까요?

**Comment by Mee-parti** [comment]
네, 컨텐츠 포스팅할때 아카이브 지정되었으면 하고, 아카이브 페이지에도 포스트 목록이 보였으면 합니다. 또 포스트에 들어가면 아카이브별로 포스트가 보였으면 합니다.

**Comment by rest515** [comment]
구현하였습니다. 나중에 테스트해보셔요.
