### ISSUE TITLE
아카이브, 포스트 수정 및 삭제 권한을 부여합니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/datapublic#39]
아카이브, 포스트 수정 삭제가 해당 게설자만 할 수 있습니다.
아카이브, 포스트 수정 및 삭제를 다 할 수 있도록 권한을 소수의 몇분에겐 부여하면 어떨까 합니다.
콘텐츠 매니저 분, 데이터팀, 비영리단체 활동가들에게 드릴까 합니다.
혹시 권한 조정이 가능할까요? 회원의 권한을 조정할 수 있는 페이지를 안내해주셔도 좋습니다.

**Comment by Mee-parti** [comment]
bombam.work@gmail.com
heyjayzo1@gmail.com
ghwjrehf@gmail.com
jp@parti.coop
mee@parti.coop
우선 권한 조정을 부탁드립니다.
될 수 있다면 페이지를 알려주시면 함께 하게 되는 비영리 단체분들께도 제가 가입하도록 안내하고 권한을 드리겠습니다.

**Comment by rest515** [comment]
네 계속 늘어나는 거라면 관리 페이지를 만들어서 알려드릴께요.
