### ISSUE TITLE
데이터퍼블릭 메인 페이지의 포스트 배치를 수정합니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/datapublic#40]
데이터퍼블릭 페이지에 포스트를 여러개 올렸는데, 배치가 이상하게 됩니다.
또 옆에 상단 바를 누르면 포스트 항목이 없습니다. 
포스트 항목 추가 및 메인페이지 배치 수정이 가능할까요?

**Comment by rest515** [comment]
수정하였습니다.
