### ISSUE TITLE
포스트 본문 비율을 변경합니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/datapublic#42]
현재 가로폭이 1110 px 이여서 텍스트 대비 이미지가 너무 크다고 합니다.
parti.coop/posts 비율처럼 가로폭(690px) 변경을 요청했습니다.

**Comment by rest515** [comment]
텍스트 대비 이미지 크기가 큰데.. 가로폭을 줄이는 이유가 무엇일까요? 
텍스트 대비 이미지 크기가 크면.. 이미지를 줄여야 하는게 아니려나요? 

혹시 어떤 페이지에서 일어나는 현상일까요?

**Comment by Mee-parti** [comment]
콘텐츠 디자인을 하시는데, 포스트 본문 가로폭이 너무 길어서 이미지만 보이는 상황이라고 해요. 그래서 빠띠 쿱 홈페이지 포스트 비율정도로 줄여달라는 요청이었습니다.

**Comment by rest515** [comment]
이미지를 현재 가로폭에 맞춰서 작업하신다는 의미인가 보네요. 본문 스타일은 나중에 한꺼번에 맞추도록 하겠습니다. 중간 제목, 볼드 정도만 활용해서 작성하시면 어떨까 싶어요.

**Comment by Mee-parti** [comment]
협력가분이 디자인해서 업로드 하시는데, 포스트 페이지 비율과 구성에 대해서 의견을 준 사항이십니다.

**Comment by rest515** [comment]
네. 빠띠 홈페이지의 글 기준으로 작업하시면 될 거 같습니다.
