### ISSUE TITLE
현재 주요 소식이나 이벤트를 메인 영역의 배너로 알립니다

### ISSUE THREAD

**Issue by rest515** [parti-coop/datapublic#43]
![image](https://user-images.githubusercontent.com/794973/97935235-52ca1f80-1dbb-11eb-8879-dc6cf8a5d755.png)

이런 영역을 추가하려고 합니다. 컨텐츠를 정리해주시면 넣어볼께요. 지금 진행중인 공유기업 사업을 넣어도 좋겠네요.

**Comment by Mee-parti** [comment]
슬라이더로 통합되어서 진행합니다.
