### ISSUE TITLE
글꼴을 쉽게 변경할 수 있도록 모든 글꼴이 보이도록 합니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/datapublic#46]
글꼴 설정을 할 때 위에 있는 글꼴이 보이지 않는 경우가 생깁니다.
스크롤을 내려서 글꼴을 설정해야 하는 상황이 벌어집니다.
간단히 변경할 수 있는 걸까요? 한번 확인 부탁드립니다.

<img width="835" alt="스크린샷 2020-12-23 오전 11 54 14" src="https://user-images.githubusercontent.com/58237640/102995025-87f52180-4563-11eb-9d02-544b0b819c5a.png">

<img width="823" alt="스크린샷 2020-12-23 오전 11 54 31" src="https://user-images.githubusercontent.com/58237640/102995031-8a577b80-4563-11eb-8243-774f2b8175a1.png">

**Comment by wagurano** [comment]
선택할 수 있는 글꼴 목록을 보여주는 기능은 에디터의 고유 기능을 사용해서 현재 반영하기 어렵습니다. 여기에 대해서는 같이 논의해보면 좋겠습니다.

**Comment by wagurano** [comment]
에디터가 지원하는 글꼴 가지수를 줄이면 한눈에 보일 수 있습니다. 고딕, 굴림 등 몇가지만 보여주면 어떠세요?
@Mee-parti

**Comment by Mee-parti** [comment]
네, 그래도 좋습니다. 지금은 글꼴을 변경하려고 하면 짤려서 보여서 쉽게 변경하기 어려워 요청드렸어요.
