### ISSUE TITLE
게시글과 아카이브 관련글 간의 여백을 조정합니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/datapublic#47]
글의 빈칸이 아님에도 아카이브 관련글을 보는데 있어서
여백이 많이 잡혀 있습니다. 조금 줄이면 어떨까요?
<img width="1053" alt="스크린샷 2020-12-23 오후 6 05 26" src="https://user-images.githubusercontent.com/58237640/102995209-e3271400-4563-11eb-83ac-b8ecb530898a.png">

**Comment by wagurano** [comment]
* [v0.1.9 배포하였습니다.](https://github.com/parti-coop/datapublic/tree/v0.1.9)
* 수정사항이 있으면 이슈를 다시 열어주세요.
