### ISSUE TITLE
썸네일 하단 게시글 제목 줄간격을 배치합니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/datapublic#48]
썸네일 아래에 있는 게시글 제목의 가독성이 떨어집니다. 
제목 줄간격을 넓게 배치할 수 있을까요?
<img width="732" alt="스크린샷 2020-12-23 오후 6 06 03" src="https://user-images.githubusercontent.com/58237640/102995283-136eb280-4564-11eb-84c4-e492b0db3e8c.png">

**Comment by wagurano** [comment]
* [v0.1.9 배포하였습니다.](https://github.com/parti-coop/datapublic/tree/v0.1.9)
* 수정사항이 있으면 이슈를 다시 열어주세요.
