### ISSUE TITLE
데이터활동가 커뮤니티 안내에 있어 색상확인과 링크확인이 필요합니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/datapublic#49]
<img width="1440" alt="스크린샷 2020-12-23 오후 9 17 35" src="https://user-images.githubusercontent.com/58237640/102995658-e1aa1b80-4564-11eb-8a93-134438c62221.png">
1. 상단에 다른 색상으로 되어 있습니다. 일부로 달리 하셨는지 여쭈어봅니다.
같은 색상으로 통일하면 어떨까 제안드립니다.

2. 하단 보더에 [빠띠 데이터 활동가 그룹]  / [시민주도로 모두의 데이터 만듭니다] 가
링크가 따로 되어 있는데, 가져다대면 전체 선택 되는 걸로 바꾸는 방법을 제안드립니다.

**Comment by wagurano** [comment]
* [v0.1.10 배포하였습니다.](https://github.com/parti-coop/datapublic/tree/v0.1.10)
* 수정사항이 있으면 이슈를 다시 열어주세요.
