### ISSUE TITLE
문의 이용약관 개인정보취급방침 표시 여부를 결정합니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/datapublic#50]
<img width="1440" alt="스크린샷 2020-12-23 오후 9 17 35" src="https://user-images.githubusercontent.com/58237640/102996071-c1c72780-4565-11eb-9a9e-c4299d479d5c.png">
문의 이용약관 개인정보취급방침이 없는 관계로 
일단 보이지 않음 처리를 하면 어떨까 합니다.

**Comment by wagurano** [comment]
* [v0.1.9 배포하였습니다.](https://github.com/parti-coop/datapublic/tree/v0.1.9)
* 수정사항이 있으면 이슈를 다시 열어주세요.
