### ISSUE TITLE
아카이브 하단에 소식 추가 버튼을 넣습니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/datapublic#51]
<img width="1440" alt="스크린샷 2020-12-23 오후 9 19 42" src="https://user-images.githubusercontent.com/58237640/102996160-ea4f2180-4565-11eb-981e-dd463acfb1f3.png">
 소식 추가 버튼을 넣으면 어떨까요?

**Comment by wagurano** [comment]
* [v0.1.9 배포하였습니다.](https://github.com/parti-coop/datapublic/tree/v0.1.9)
* 수정사항이 있으면 이슈를 다시 열어주세요.
