### ISSUE TITLE
아카이브 하단에 활용사례 부분을 추가합니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/datapublic#52]
활용사례 부분이 빠져 있습니다.
데이터와 함께 보여지는 방식으로 하면 어떨까 합니다.
<img width="1440" alt="스크린샷 2020-12-23 오후 9 19 42" src="https://user-images.githubusercontent.com/58237640/102996297-38fcbb80-4566-11eb-936e-ea8e1d3b3c88.png">

**Comment by wagurano** [comment]
* [v0.1.9 배포하였습니다.](https://github.com/parti-coop/datapublic/tree/v0.1.9)
* 수정사항이 있으면 이슈를 다시 열어주세요.
