### ISSUE TITLE
데이터 추가란에 관련정보 항목 추가를 활용사례로 변경합니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/datapublic#53]
디자인 구석구석이 너무나도 마음에 들고 편리합니다.
[관련정보 항목 추가]를 [활용사례 추가]로 변경하면 어떨까요?
<img width="757" alt="스크린샷 2020-12-23 오후 9 32 24" src="https://user-images.githubusercontent.com/58237640/102996500-93961780-4566-11eb-9628-fca2e11a3dc9.png">

**Comment by wagurano** [comment]
* [v0.1.10 배포하였습니다.](https://github.com/parti-coop/datapublic/tree/v0.1.10)
* 수정사항이 있으면 이슈를 다시 열어주세요.
