### ISSUE TITLE
아카이브가 열리지 않습니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/datapublic#93]
https://datapublic.kr/archives/67
<img width="1152" alt="스크린샷 2021-12-21 오후 8 07 51" src="https://user-images.githubusercontent.com/58237640/146920239-13ab74c4-6d5e-4aa8-9ac5-005563ff7e71.png">

**Comment by Mee-parti** [comment]
https://datapublic.kr/archives/67로 되어 있던 아카이브가 수정되면서, https://datapublic.kr/archives/68 로 되서 안되는 걸로 파악됩니다.

**Comment by dalikim** [comment]
네 그럼 이 이슈는 닫을게요
